/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Boards {
  board_id: Generated<string>;
  budget: Numeric;
  created_at: Generated<Timestamp>;
  name: string;
  user_id: string;
  value: Numeric;
}

export interface Sessions {
  expires_at: Generated<Timestamp>;
  session: Json;
  session_id: Generated<string>;
}

export interface Tasks {
  board_id: string;
  code: string;
  completed: Generated<boolean>;
  cost: Numeric;
  created_at: Generated<Timestamp>;
  position: number;
  predecessors_ids: string[] | null;
  steps: number;
  task_id: Generated<string>;
  title: string;
  user_id: string;
  value: Numeric;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  hashed_password: string;
  user_id: Generated<string>;
}

export interface DB {
  boards: Boards;
  sessions: Sessions;
  tasks: Tasks;
  users: Users;
}
